version: '3'

services:
  asp.net_core_2.0_web_application_web_mvc_with_docker:
    image: aspnetcore20webapplicationwebmvcwithdocker:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_asp.net_core_2.0_web_application_web_mvc_with_docker$
    volumes:
      - C:\SOURCES\VsProjectTypeRepository\ASP.NET_Core_2.0_Web_Application_Web_MVC_with_Docker:C:\app
      - C:\Users\Jura.Gorohovsky\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_asp.net_core_2.0_web_application_web_mvc_with_docker$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_asp.net_core_2.0_web_application_web_mvc_with_docker$ bin\\Debug\\netcoreapp2.0\\ASP.NET_Core_2.0_Web_Application_Web_MVC_with_Docker.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"
